name: Minishell test
run-name: Checking if pr by ${{ github.actor }} passes all tests
on:
  push:
    branches: [ jvan-hal ]
jobs:
  builtin_unit-test:
    timeout-minutes: 10
    runs-on: macos-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install dependencies
      run: brew install criterion
    - name: Run cd tests
      run: make test_cd
    - name: Run echo tests
      run: make test_echo
    - name: Run env tests
      run: make test_env
    - name: Run export tests
      run: make test_export
    - name: Run pwd tests
      run: make test_pwd
    - name: Run unset tests
      run: make test_unset
  # parser_unit-test:
  #   timeout-minutes: 10
  #   runs-on: macos-latest
  #   steps:
  #   - name: Clone repository
  #     uses: actions/checkout@v3
  #     with:
  #       submodules: true
  #   - name: Install dependencies
  #     run: brew install criterion
#    - name: Run lexer tests
#      run: make test_lexer
#    - name: Run expander tests
#      run: make test_expander
    # - name: Run parser tests
    #   run: make test_parser
  utils_unit-test:
    timeout-minutes: 10
    runs-on: macos-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install dependencies
      run: brew install criterion
    - name: Run env tests
      run: make test_msh_env
  full_test:
    timeout-minutes: 10
    runs-on: macos-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Run full minishell test
      run: ./test/msh/integration/msh_test.sh
