name: minishell test
run-name: checking if pr by ${{ github.actor }} passes all tests
on:
  push:
    branches: [ jvan-hal ]
jobs:
  builtin_unit-test:
    timeout-minutes: 10
    runs-on: macos-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install Dependencies
      run: brew install criterion
    - name: run cd tests
      run: make test_cd
    - name: run echo tests
      run: make test_echo
    - name: run env tests
      run: make test_env
    - name: run export tests
      run: make test_export
    - name: run pwd tests
      run: make test_pwd
    - name: run unset tests
      run: make test_unset
  # parser_unit-test:
  #   timeout-minutes: 10
  #   runs-on: macos-latest
  #   steps:
  #   - name: Clone repository
  #     uses: actions/checkout@v3
  #     with:
  #       submodules: true
  #   - name: Install Dependencies
  #     run: brew install criterion
#    - name: run lexer tests
#      run: make test_lexer
#    - name: run expander tests
#      run: make test_expander
    # - name: run parser tests
    #   run: make test_parser
  utils_unit-test:
    timeout-minutes: 10
    runs-on: macos-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install Dependencies
      run: brew install criterion
    - name: run env tests
      run: make test_msh_env
