name: minishell test
run-name: checking if pr by ${{ github.actor }} passes all tests
on:
  pull_request:
    branches: [ master ]
jobs:
  unit-test:
    timeout-minutes: 10
    runs-on: macos-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install Dependencies
      run: |
        brew update
        brew install criterion
    - name: run echo tests
      run: make test_echo
    - name: run pwd tests
      run: make test_pwd
